apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redis-insight
commonLabels:
  app.kubernetes.io/name: redis-insight
resources:
  - namespace.yaml
  - rbac.yaml
  - persistence.yaml
  - ingress.yaml
  - deployment.yaml
