apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: greenstar-nats
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: nats
      version: 0.19.13
      sourceRef:
        kind: HelmRepository
        name: greenstar-nats
  values:
    nats:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 100m
          memory: 128Mi
      jetstream:
        enabled: true
        memStorage:
          enabled: true
          size: 1Gi
        fileStorage:
          enabled: true
          storageDirectory: /data
          size: 1Gi
          accessModes:
            - ReadWriteOnce
    natsbox:
      resources:
        requests:
          cpu: 100m
          memory: 16Mi
        limits:
          cpu: 100m
          memory: 16Mi

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
