apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  labels:
    app.kubernetes.io/component: notification-controller
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/version: v2.0.0-rc.1
    control-plane: controller
  name: webhook-flux-kfirs-com-a
  namespace: flux-system
spec:
  name: webhook.flux.${gke_cluster_name}.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    namespace: dns
    name: kfirs-com
  rrdatasRefs:
    - external: traefik.${gke_cluster_name}.kfirs.com.
