apiVersion: v1
kind: ConfigMap
metadata:
  name: external-secrets-values
  namespace: external-secrets
data:
  values.yaml: |
    installCRDs: true
    crds:
      createClusterExternalSecret: true
      createClusterSecretStore: true
    concurrent: 1
    resources:
      requests:
        cpu: 50m
        memory: 32Mi
      limits:
        cpu: 200m
        memory: 64Mi
    nodeSelector:
      gke.kfirs.com/purpose: workloads
    tolerations:
      - effect: NoExecute
        key: gke.kfirs.com/purpose
        operator: Equal
        value: workloads
    webhook:
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
    certController:
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 200m
          memory: 64Mi
