apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emissary-ingress
spec:
  interval: 5m
  timeout: 1h
  chart:
    spec:
      chart: emissary-ingress
      version: 8.6.0
      sourceRef:
        kind: HelmRepository
        name: datawire

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
