apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arik-kfir
  name: arik-simplify-deployment
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-arik-simplify-deployment
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
    - name: cert-manager-issuer
    - name: cnrm
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  force: true
  path: apps
  targetNamespace: arik-simplify-deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      env: arik-simplify-deployment
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
  images:
    - name: ghcr.io/arik-kfir/greenstar/backend
      newTag: 7c1fe7eb87699a6fba7ab39d7c4936558bc3ef19
    - name: ghcr.io/arik-kfir/greenstar/frontend
      newTag: 7c1fe7eb87699a6fba7ab39d7c4936558bc3ef19
