apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-arik-simplify-deployment
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
    - name: cert-manager-issuer
    - name: cnrm
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  force: true
  path: apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      env: arik-simplify-deployment
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
  images:
    - name: ghcr.io/arik-kfir/greenstar/backend
      newTag: 8e50628366adbf57dac769fb9735f93bcd711b3f
    - name: ghcr.io/arik-kfir/greenstar/frontend
      newTag: 8e50628366adbf57dac769fb9735f93bcd711b3f
