apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: greenstar-arik-simplify-deployment
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: arik/simplify-deployment
  secretRef:
    name: flux-system
  url: ssh://git@github.com/arik-kfir/greenstar
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arik-kfir
  name: arik-simplify-deployment
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-arik-simplify-deployment
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
    - name: cert-manager-issuer
    - name: cnrm
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  force: true
  path: deploy/cluster
  targetNamespace: arik-simplify-deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: greenstar-arik-simplify-deployment
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      env: arik-simplify-deployment
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
