apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-drop-nginx
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
    - name: cert-manager-issuer
    - name: cnrm
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  force: true
  path: apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      env: drop-nginx
    substituteFrom:
      - kind: ConfigMap
        name: cluster-info
        optional: false
  images:
    - name: ghcr.io/arik-kfir/greenstar/backend
      newTag: a6679057d982d77102be0d3360bc8c093977b41a
    - name: ghcr.io/arik-kfir/greenstar/frontend
      newTag: a6679057d982d77102be0d3360bc8c093977b41a
