apiVersion: v1
kind: Namespace
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arik-kfir
  name: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps-main
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
    - name: cert-manager-issuer
    - name: cnrm
    - name: dns
    - name: external-secrets
    - name: traefik
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  force: true
  path: apps/skeleton
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      - name: env
        value: main
      - name: gke_cluster_name
        value: main
      - name: gke_cluster_region
        value: me-west1 # TODO: infrastructure repository should update this value automatically via GitOps workflow
