apiVersion: v1
kind: ConfigMap
metadata:
  name: actions-runner-controller-values
  namespace: arc
data:
  values.yaml: |
    logFormat: json
    defaultScaleDownDelay: 3m
    authSecret:
      enabled: true
      create: false
    runner:
      statusUpdateHook:
        enabled: true
    serviceAccount:
      create: false
      name: actions-runner-controller
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
      limits:
        cpu: 100m
        memory: 50Mi
    nodeSelector:
      gke.kfirs.com/purpose: workloads
    tolerations:
      - effect: NoExecute
        key: gke.kfirs.com/purpose
        operator: Equal
        value: workloads
    githubWebhookServer:
      enabled: true
      replicaCount: 1
      logFormat: json
      secret:
        enabled: true
        create: false
        name: "actions-runner-controller-secret-values"  # TODO: what key?
      serviceAccount:
        create: false
        name: actions-runner-controller
      resources:
        requests:
          cpu: 100m
          memory: 50Mi
        limits:
          cpu: 100m
          memory: 50Mi
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
          
