apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: arc
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: actions-runner-controller
      version: 0.23.1
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
  valuesFrom:
    - kind: ConfigMap
      name: actions-runner-controller-values
      optional: false
    - kind: Secret
      name: actions-runner-controller-secret-values
      targetPath: authSecret.github_app_private_key
      valuesKey: github-app_arik-kfir-arc_privatekey
      optional: false

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true

  # TODO: create "actions-runner-controller-secret-values" secret via external-secrets
  #       it should contain the github-app_arik-kfir-arc_privatekey key and the github-app_arik-kfir-arc_webhook-secret
