apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerSet
metadata:
  name: set-large
  namespace: arc
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: arc
      app.kubernetes.io/component: large-runner-set
  organization: arik-kfir
  serviceName: set-large
  template:
    metadata:
      labels:
        app.kubernetes.io/name: arc
        app.kubernetes.io/component: large-runner-set
    spec:
      containers:
        - name: docker
          env:
            - name: DOCKER_GROUP_GID
              value: "1001"
          resources:
            limits:
              cpu: 3
              memory: 7Gi
            requests:
              cpu: 3
              memory: 7Gi
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - effect: NoExecute
          key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: set-large-autoscaler
  namespace: arc
spec:
  scaleDownDelaySecondsAfterScaleOut: 60
  scaleTargetRef:
    kind: RunnerSet
    name: set-large
  minReplicas: 0
  maxReplicas: 3
  scaleUpTriggers:
    - githubEvent:
        workflowJob: {}
      amount: 1
      duration: 60m
