apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cnrm
  namespace: default
spec:
  interval: 5m
  timeout: 5m
  retryInterval: 1m
  path: platform/cnrm
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
