apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dns
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
    - name: cnrm
  interval: 5m
  timeout: 5m
  retryInterval: 5m
  force: true
  path: platform/dns
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
