apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: emissary-ingress
  namespace: default
spec:
  dependsOn:
    - name: emissary-system
  interval: 5m
  timeout: 10m
  path: platform/emissary/ingress
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
