apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: default
spec:
  dependsOn:
    - name: cnrm
  interval: 5m
  timeout: 20m # LoadBalancer service might take a little while to sync in GCP
  path: platform/traefik/server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  patches:
    - patch: |-
        - op: replace
          path: /spec/resourceID
          value: gke-ingress-main
      target:
        group: compute.cnrm.cloud.google.com
        version: v1beta1
        kind: ComputeAddress
        name: gke-ingress
        namespace: traefik
    - patch: |-
        - op: replace
          path: /spec/name
          value: traefik.main.kfirs.com.
      target:
        group: dns.cnrm.cloud.google.com
        version: v1beta1
        kind: DNSRecordSet
        name: traefik-kfirs-com-a
        namespace: traefik
