apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: traefik
  namespace: default
spec:
  dependsOn:
    - name: cnrm
  interval: 5m
  timeout: 10m # LoadBalancer service might take a little while to sync in GCP
  retryInterval: 1m
  force: true
  path: platform/traefik/server
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  postBuild:
    substitute:
      gke_cluster_name: main
      gke_cluster_region: me-west1 # TODO: infrastructure repository should update this value automatically via GitOps workflow
      gke_ingress_ip: 34.165.202.152
