apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: neo4j-kfirs-com
spec:
  secretName: neo4j-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - neo4j.default.kfirs.com
