apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  name: neo4j-kfirs-com-a
spec:
  name: neo4j.default.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    external: kfirs-com
  rrdatasRefs:
    - external: traefik.main.kfirs.com.
