apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: greenstar-backend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: greenstar-backend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: backend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: backend
  name: greenstar-backend
spec:
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app.kubernetes.io/component: backend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: backend
    spec:
      containers:
        - image: ghcr.io/arik-kfir/greenstar/backend:latest
          name: backend
          env:
            - name: AUTH_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: greenstar-secrets
                  key: auth0_domain
                  optional: false
            - name: AUTH_AUTH0_API_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: greenstar-secrets
                  key: auth0_api_client_id
                  optional: false
            - name: AUTH_AUTH0_API_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: greenstar-secrets
                  key: auth0_api_client_secret
                  optional: false
          startupProbe:
            httpGet:
              port: http
              path: /healthz
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              port: http
              path: /healthz
            failureThreshold: 3
            periodSeconds: 3
            terminationGracePeriodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 8000
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 32Mi
            requests:
              cpu: 100m
              memory: 16Mi
          volumeMounts: []
      enableServiceLinks: false
      serviceAccountName: greenstar-backend
      volumes: []
