apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: greenstar-frontend
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: greenstar-frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/component: frontend
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: frontend
  name: greenstar-frontend
spec:
  progressDeadlineSeconds: 300
  selector:
    matchLabels:
      app.kubernetes.io/component: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/component: frontend
    spec:
      containers:
        - image: ghcr.io/arik-kfir/greenstar/frontend:latest
          name: frontend
          env:
            - name: REACT_APP_AUTH0_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: greenstar-secrets
                  key: auth0_domain
                  optional: false
            - name: REACT_APP_AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: greenstar-secrets
                  key: auth0_app_client_id
                  optional: false
          startupProbe:
            httpGet:
              port: http
              path: /index.html
            failureThreshold: 6
            periodSeconds: 10
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              port: http
              path: /index.html
            failureThreshold: 3
            periodSeconds: 3
            terminationGracePeriodSeconds: 10
            timeoutSeconds: 1
          ports:
            - containerPort: 80
              name: http
          resources:
            limits:
              cpu: 1000m
              memory: 128Gi
            requests:
              cpu: 200m
              memory: 64Mi
      enableServiceLinks: false
      serviceAccountName: greenstar-frontend
