apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - image: redis/redis-stack:7.0.6-RC8
          name: redis
          args:
            - --port=6380
            - --tls-port=6379
            - --tls-cert-file=/etc/redis/tls/tls.crt
            - --tls-key-file=/etc/redis/tls/tls.key
            - --tls-auth-clients=no
            - --tls-replication=no
            - --tls-cluster=no
          env:
            - name: REDIS_TLS_CERT_FILE
              valueFrom:
                secretKeyRef:
                  name: redis-kfirs-com-tls
                  key: tls.crt
            - name: REDIS_TLS_KEY_FILE
              valueFrom:
                secretKeyRef:
                  name: redis-kfirs-com-tls
                  key: tls.key
          ports:
            - containerPort: 6379
              name: client-tls
            - containerPort: 6380
              name: client-nontls
            - containerPort: 8001
              name: http
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - '[[ "$(redis-cli PING)" == "PONG" ]]'
            failureThreshold: 30
            periodSeconds: 5
            terminationGracePeriodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - '[[ "$(redis-cli PING)" == "PONG" ]]'
            failureThreshold: 3
            periodSeconds: 5
            terminationGracePeriodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              port: 8001
            successThreshold: 1
            initialDelaySeconds: 10
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 200m
              memory: 128Mi
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: false
            - name: tls
              mountPath: /etc/redis/tls
              readOnly: true
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      tolerations:
        - key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
          effect: NoExecute
      serviceAccountName: redis
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redis
            readOnly: false
        - name: tls
          secret:
            secretName: redis-kfirs-com-tls
            optional: false
