apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: greenstar-${env}-public
spec:
  messageRetentionDuration: 604800s # 7 days
  messageStoragePolicy:
    allowedPersistenceRegions:
      - me-west1
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: greenstar-${env}-public-dl
spec:
  messageRetentionDuration: 2592000s # 30 days
  messageStoragePolicy:
    allowedPersistenceRegions:
      - me-west1
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: greenstar-${env}-public-backend
spec:
  ackDeadlineSeconds: 600
  deadLetterPolicy:
    deadLetterTopicRef:
      name: greenstar-${env}-public-dl
    maxDeliveryAttempts: 10
  enableExactlyOnceDelivery: true
  enableMessageOrdering: true
  expirationPolicy:
    ttl: ""
  messageRetentionDuration: 86400s # 1 day
  retainAckedMessages: false
  retryPolicy:
    maximumBackoff: 600s
    minimumBackoff: 5s
  topicRef:
    name: greenstar-${env}-public
