apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: greenstar-${env}-admin
spec:
  messageRetentionDuration: "7d"
  messageStoragePolicy:
    allowedPersistenceRegions:
      - me-west1
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: greenstar-${env}-admin-dl
spec:
  messageRetentionDuration: "30d"
  messageStoragePolicy:
    allowedPersistenceRegions:
      - me-west1
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: greenstar-${env}-admin-backend
spec:
  ackDeadlineSeconds: 600
  deadLetterPolicy:
    deadLetterTopicRef:
      name: greenstar-${env}-admin-dl
    maxDeliveryAttempts: 10
  enableExactlyOnceDelivery: true
  enableMessageOrdering: true
  expirationPolicy:
    ttl: ""
  messageRetentionDuration: "1d"
  retainAckedMessages: false
  retryPolicy:
    maximumBackoff: "600"
    minimumBackoff: "5"
  topicRef:
    name: greenstar-${env}-admin
