apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: greenstar-backend
spec:
  resourceID: gs-bck-${env:0:23}
  displayName: greenstar-backend-${env}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: greenstar-backend-ksa-link
spec:
  member: serviceAccount:arik-kfir.svc.id.goog[${env}/greenstar-backend]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: greenstar-backend
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: greenstar-backend-pubsub-subscriber
spec:
  memberFrom:
    serviceAccountRef:
      name: greenstar-backend
  role: roles/pubsub.subscriber
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${gcp_project_number}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: greenstar-backend-pubsub-publisher
spec:
  memberFrom:
    serviceAccountRef:
      name: greenstar-backend
  role: roles/pubsub.publisher
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${gcp_project_number}
