apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ingress.yaml
  - gcp-pubsub-admin.yaml
  - gcp-pubsub-operations.yaml
  - gcp-pubsub-public.yaml
  - secrets.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/nodeSelector
        value:
          gke.kfirs.com/purpose: workloads
      - op: replace
        path: /spec/template/spec/tolerations
        value:
          - key: gke.kfirs.com/purpose
            operator: Equal
            value: workloads
            effect: NoExecute
  - target:
      group: ""
      version: v1
      kind: Service
      name: greenstar-redis
    patch: |-
      - op: add
        path: /spec/ports/-
        value:
          name: client-tls
          port: 6380
          protocol: TCP
          targetPort: client-tls
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: greenstar-redis
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: REDIS_ARGS
          value: >-
            --tls-auth-clients no
            --tls-replication no
            --tls-cluster no
            --tls-port 6380
            --tls-cert-file /etc/redis/tls/tls.crt
            --tls-key-file /etc/redis/tls/tls.key
      - op: add
        path: /spec/template/spec/containers/0/ports/-
        value:
          containerPort: 6380
          name: client-tls
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts/-
        value:
          name: tls
          mountPath: /etc/redis/tls
          readOnly: true
      - op: add
        path: /spec/template/spec/volumes/-
        value:
          name: tls
          secret:
            secretName: greenstar-redis-kfirs-com-tls
            optional: false
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: greenstar-backend
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: info
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: DEV_MODE
          value: "false"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NEO4J_HOST
          value: neo4j.neo4j.svc.cluster.local
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NEO4J_PORT
          value: "7687"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GCP_PROJECT_ID
          value: ${gcp_project_id}
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GCP_ADMIN_SUBSCRIPTION
          value: greenstar-${env}-admin-backend
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GCP_OPERATIONS_SUBSCRIPTION
          value: greenstar-${env}-operations-backend
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: GCP_PUBLIC_SUBSCRIPTION
          value: greenstar-${env}-public-backend
