apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: secrets
  name: greenstar-secrets
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: greenstar-secrets
spec:
  resourceID: gs-sec-${env}
  displayName: greenstar-secrets-${env}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: greenstar-secrets-ksa-link
spec:
  member: serviceAccount:arikkfir.svc.id.goog[${env}/greenstar-secrets]
  role: roles/iam.workloadIdentityUser
  resourceRef:
    apiVersion: iam.cnrm.cloud.google.com/v1beta1
    kind: IAMServiceAccount
    name: greenstar-secrets
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: greenstar-secrets-secret-viewer
spec:
  memberFrom:
    serviceAccountRef:
      name: greenstar-secrets
  role: roles/secretmanager.viewer
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${gcp_project_number}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: greenstar-secrets-secret-accessor
spec:
  memberFrom:
    serviceAccountRef:
      name: greenstar-secrets
  role: roles/secretmanager.secretAccessor
  resourceRef:
    apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
    kind: Project
    external: projects/${gcp_project_number}
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: greenstar-gcpsm
spec:
  provider:
    gcpsm:
      projectID: arik-kfir
      auth:
        workloadIdentity:
          clusterLocation: ${gke_cluster_zone}
          clusterName: ${gke_cluster_name}
          serviceAccountRef:
            name: greenstar-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: greenstar-secrets
spec:
  refreshInterval: 30m
  secretStoreRef:
    kind: SecretStore
    name: greenstar-gcpsm
  data:
    - secretKey: auth0_domain
      remoteRef:
        key: auth0_domain
    - secretKey: auth0_api_client_id
      remoteRef:
        key: auth0_api_client_id
    - secretKey: auth0_api_client_secret
      remoteRef:
        key: auth0_api_client_secret
    - secretKey: auth0_app_client_id
      remoteRef:
        key: auth0_app_client_id
