apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - emissary-crds-3.6.0.yaml
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: emissary-apiext
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
