apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: gke-ingress
  namespace: traefik
spec:
  resourceID: gke-ingress
  addressType: EXTERNAL
  description: GKE Ingress
  ipVersion: IPV4
  location: me-west1 # TODO: this should be inferred from infrastructure variable
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  name: traefik-kfirs-com-a
  namespace: traefik
spec:
  name: traefik.kfirs.com.
  type: A
  ttl: 300
  managedZoneRef:
    name: kfirs-com
    namespace: dns
  rrdatasRefs:
    - kind: ComputeAddress
      name: gke-ingress
