apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 1h
  chart:
    spec:
      chart: traefik
      version: 22.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      optional: false
    - kind: ConfigMap
      name: traefik-values
      valuesKey: gke-ingress-ip-address
      targetPath: service.spec.loadBalancerIP
      optional: true

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
