apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 5m
  timeout: 1h
  chart:
    spec:
      chart: traefik
      version: 22.1.0
      sourceRef:
        kind: HelmRepository
        name: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-values
      optional: false
  values:
    service:
      loadBalancerSourceRanges:
        - 192.30.252.0/22
        - 185.199.108.0/22
        - 140.82.112.0/20
        - 143.55.64.0/20
        - 85.64.218.35/32
        - 149.106.226.215/32
      spec:
        loadBalancerIP: 34.165.10.103
  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
