apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-values
  namespace: traefik
data:
  values.yaml: |
    nodeSelector:
      gke.kfirs.com/purpose: workloads
    tolerations:
      - effect: NoExecute
        key: gke.kfirs.com/purpose
        operator: Equal
        value: workloads
    ingressRoute:
      dashboard:
        enabled: false
    readinessProbe:
      periodSeconds: 120
    livenessProbe:
      periodSeconds: 120
    providers:
      kubernetesCRD:
        enabled: true
        allowCrossNamespace: true
        allowExternalNameServices: true
        allowEmptyServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        allowEmptyServices: true
        ingressClass: traefik
    logs:
      general:
        format: json
        level: INFO
      access:
        enabled: true
        format: json
        fields:
          defaultMode: keep
          general:
            defaultmode: keep
          headers:
            defaultmode: keep
    ports:
      web:
        redirectTo: websecure
      redis:
        port: 6380
        containerPort: 6380
        expose: true
        exposedPort: 6380
        targetPort: 6380
        protocol: TCP
        http3:
          enabled: false
        advertisedPort: 6380
        tls:
          enabled: true
      bolt:
        port: 7688
        containerPort: 7688
        expose: true
        exposedPort: 7688
        targetPort: 7688
        protocol: TCP
        http3:
          enabled: false
        advertisedPort: 7688
        tls:
          enabled: true
    service:
      spec:
        externalTrafficPolicy: Local
    autoscaling:
      enabled: true
      minReplicas: 1
      maxReplicas: 3
      metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 60
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 60
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 300
          policies:
            - type: Pods
              value: 1
              periodSeconds: 60
    resources:
      requests:
        cpu: 200m
        memory: 100Mi
      limits:
        cpu: 500m
        memory: 200Mi
