apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: neo4j
commonLabels:
  app.kubernetes.io/name: neo4j
resources:
  - namespace.yaml
  - rbac.yaml
  - persistence.yaml
  - service.yaml
  - deployment.yaml
