apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: arc
  namespace: default
spec:
  dependsOn:
    - name: cnrm
    - name: external-secrets
  interval: 5m
  timeout: 10m
  path: arc
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
