apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nack
spec:
  interval: 5m
  timeout: 5m
  chart:
    spec:
      chart: nack
      version: 0.21.0
      sourceRef:
        kind: HelmRepository
        name: nats
  values:
    jetstream:
      enabled: true
      nats:
        url: nats://nats:4222
    resources:
      requests:
        cpu: 100m
        memory: 16Mi
      limits:
        cpu: 100m
        memory: 16Mi

  # This prevents "reconciliation failed: install retries exhausted" errors
  install:
    disableWait: true
  upgrade:
    disableWait: true
