apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nats
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release-nats.yaml
  - helm-release-nack.yaml
  - service.yaml
