apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nats
resources:
  - namespace.yaml
  - helm-repository.yaml
  - https://raw.githubusercontent.com/nats-io/nack/v0.10.1/deploy/crds.yml
  - helm-release-nack.yaml
  - helm-release-nats.yaml
  - service.yaml
