apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nats
resources:
  - namespace.yaml
  - helm-repository.yaml
  - https://github.com/nats-io/nack//deploy/crds.yml?ref=v0.10.1
  - helm-release-nack.yaml
  - helm-release-nats.yaml
  - service.yaml
