name: Deploy app images

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Target application environment (usually corresponds to a source branch name; e.g. "main").
        required: true
      images:
        type: string
        description: |
          Map of images to deploy, in YAML format of "image: tag" pairs, for example:
          ```
          my-image: newTag
          my-2nd-image: new2ndTag
          ```
        required: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  slug-environment:
    name: "Slug"
    runs-on: ubuntu-22.04
    outputs:
      slug: ${{ steps.slug.outputs.slug }}
    steps:
      - id: slug
        run: |
          SLUG=$(echo -n "${{ inputs.environment }}" | sed -E 's/[^a-zA-Z0-9_]+/-/g' | sed -E 's/^-|-$//g' | tr '[:upper:]' '[:lower:]')
          echo "slug=${SLUG}" >> "$GITHUB_OUTPUT"

  update:
    name: Update files
    needs: slug-environment
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment: ${{ needs.slug-environment.outputs.slug }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arik-kfir/delivery
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |-
          cat > images.yaml <<EOF
          ${{ inputs.images }}
          EOF
          if [[ ! -f "${ENV_FILE}" ]]; then
            cat etc/env-template.yaml | envsubst > "${ENV_FILE}"
          fi
          keys=($(yq e 'keys | .[]' images.yaml))
          for KEY in "${keys[@]}"; do
            TAG=$(yq e ".${KEY}" images.yaml)
            yq e -P -i 'select(.kind=="Kustomization") | del( .spec.images[] | select(.name == env(KEY)) )' "${ENV_FILE}"
            yq e -P -i 'select(.kind=="Kustomization").spec.images += {name:env(KEY),newTag:env(TAG)}' "${ENV_FILE}"
          done
        env:
          ENV_FILE: clusters/main/apps/${{ needs.slug-environment.outputs.slug }}.yaml
          ENVIRONMENT: ${{ needs.slug-environment.outputs.slug }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: clusters/main/apps
          author_name: GitHub Actions
          author_email: <gha@kfirs.com>
          message: Update images for "${{ inputs.environment }}" environment
