name: Deploy to application environment

on:
  workflow_call:
    inputs:
      branch:
        type: string
        description: Source branch to monitor for deployment.
        required: true
      environment:
        type: string
        description: Target application environment to deploy to (usually corresponds to a source branch name; e.g. "main").
        required: true

defaults:
  run:
    shell: bash -exuo pipefail {0}

jobs:

  slug-environment:
    name: "Slug"
    runs-on: ubuntu-22.04
    outputs:
      slug: ${{ steps.slug.outputs.slug }}
    steps:
      - id: slug
        run: |
          SLUG=$(echo -n "${{ inputs.environment }}" | sed -E 's/[^a-zA-Z0-9_]+/-/g' | sed -E 's/^-|-$//g' | tr '[:upper:]' '[:lower:]')
          echo "slug=${SLUG}" >> "$GITHUB_OUTPUT"

  update-files:
    name: Update files
    needs: slug-environment
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    environment: ${{ needs.slug-environment.outputs.slug }}
    steps:
      - uses: actions/checkout@v3
        with:
          repository: arik-kfir/delivery
          token: ${{ secrets.DEPLOY_APPS_PAT }}
      - run: |-
          if [[ ! -f "${ENV_FILE}" ]]; then
            cat etc/env-template.yaml | envsubst > "${ENV_FILE}"
          fi
        env:
          BRANCH: ${{ inputs.branch }}
          ENV_FILE: clusters/main/apps/${{ needs.slug-environment.outputs.slug }}.yaml
          ENVIRONMENT: ${{ needs.slug-environment.outputs.slug }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: clusters/main/apps
          author_name: GitHub Actions
          author_email: <gha@kfirs.com>
          message: Deploy to application environment "${{ inputs.environment }}"
