name: Sync Traefik LoadBalancer IP address
on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *
  push:
    branches:
      - main
    paths:
      - .github/workflows/sync-traefik-lb-address.yml
defaults:
  run:
    shell: bash -exuo pipefail {0}
env:
  FLUXCD_VERSION: 2.0.0-rc.1
  GCP_CLI_VERSION: 426.0.0
  GCP_SERVICE_ACCOUNT: delivery@arik-kfir.iam.gserviceaccount.com
  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/887552287733/locations/global/workloadIdentityPools/github-actions/providers/default
  GKE_CLUSTER_NAME: main
  GKE_CLUSTER_LOCATION: me-west1-a
concurrency:
  group: production
  cancel-in-progress: false
jobs:
  sync-traefik-lb:
    name: Sync Traefik LoadBalancer
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}
      - uses: google-github-actions/setup-gcloud@v1
        with:
          version: ${{ env.GCP_CLI_VERSION }}
      - uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: ${{ env.GKE_CLUSTER_NAME }}
          location: ${{ env.GKE_CLUSTER_LOCATION }}
      - run: |
          sudo curl -sSL -o /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/v4.33.3/yq_linux_amd64"
          sudo chmod +x /usr/local/bin/yq
      - id: ip
        run: |
          kubectl wait -n traefik --for=condition=Ready ComputeAddress/gke-ingress --timeout=5m
          echo "traefik_ip=$(kubectl get -n traefik ComputeAddress/gke-ingress -ojsonpath='{.spec.address}')" >> "$GITHUB_OUTPUT"
          echo "whitelist=$(curl -sSL https://api.github.com/meta | jq '.hooks' | yq 'filter(. != "*::*") + env(STATIC_IP_WHITELIST)')" >> "$GITHUB_OUTPUT"
        env:
          STATIC_IP_WHITELIST: '["85.64.218.35/32", "149.106.226.215/32"]'
      - run: |-
          yq e -P -i '.spec.postBuild.substitute.gke_ingress_ip=env(TRAEFIK_IP)' clusters/main/platform/traefik-server.yaml
          yq e -P -i '.spec.values.service.loadBalancerSourceRanges=env(WHITELIST)' platform/traefik/server/helm-release.yaml
          yq e -P -i '.spec.ipWhiteList.sourceRange=env(WHITELIST)' platform/traefik/server/middleware-ip-whitelist.yaml
          yq e -P -i '.spec.ipWhiteList.sourceRange=env(WHITELIST)' platform/traefik/server/middleware-ip-whitelist-tcp.yaml
        env:
          TRAEFIK_IP: ${{ steps.ip.outputs.traefik_ip }}
          WHITELIST: ${{ steps.ip.outputs.whitelist }}
      - uses: EndBug/add-and-commit@v9
        with:
          add: platform/traefik/server
          author_name: GitHub Actions
          author_email: <gha@kfirs.com>
          message: Sync GKE ingress IP whitelist addresses
