apiVersion: apps/v1
kind: Deployment
metadata:
  name: greenstar-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: redis
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: redis
    spec:
      containers:
        - image: redis/redis-stack-server:7.0.6-RC8
          name: redis
          env:
            - name: REDIS_ARGS
              value: >-
                --port 6379
                --tls-port 6380
                --tls-cert-file /etc/redis/tls/tls.crt
                --tls-key-file /etc/redis/tls/tls.key
                --tls-auth-clients no
                --tls-replication no
                --tls-cluster no
          ports:
            - containerPort: 6379
              name: client-nontls
            - containerPort: 6380
              name: client-tls
          startupProbe:
            exec:
              command:
                - bash
                - -c
                - '[[ "$(redis-cli PING)" == "PONG" ]]'
            failureThreshold: 30
            periodSeconds: 5
            terminationGracePeriodSeconds: 60
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - '[[ "$(redis-cli PING)" == "PONG" ]]'
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 5
            terminationGracePeriodSeconds: 60
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - bash
                - -c
                - '[[ "$(redis-cli PING)" == "PONG" ]]'
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
            terminationGracePeriodSeconds: 60
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
            requests:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - mountPath: /data
              name: data
              readOnly: false
            - name: tls
              mountPath: /etc/redis/tls
              readOnly: true
      enableServiceLinks: false
      nodeSelector:
        gke.kfirs.com/purpose: workloads
      serviceAccountName: greenstar-redis
      tolerations:
        - key: gke.kfirs.com/purpose
          operator: Equal
          value: workloads
          effect: NoExecute
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: greenstar-redis
            readOnly: false
        - name: tls
          secret:
            secretName: greenstar-redis-kfirs-com-tls
            optional: false
