apiVersion: v1
kind: Service
metadata:
  name: greenstar-redis
spec:
  ports:
    - name: client
      port: 6379
      protocol: TCP
      targetPort: client-nontls
  selector:
    app.kubernetes.io/name: greenstar
    app.kubernetes.io/component: redis
  type: ClusterIP
