apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: greenstar-redis-kfirs-com
spec:
  secretName: greenstar-redis-kfirs-com-tls
  issuerRef:
    kind: ClusterIssuer
    name: google-clouddns
  dnsNames:
    - greenstar-redis.default.kfirs.com
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: arikkfir
  name: greenstar-redis-kfirs-com-a
spec:
  name: greenstar-redis.default.kfirs.com.
  type: CNAME
  ttl: 300
  managedZoneRef:
    namespace: dns
    name: kfirs-com
  rrdatasRefs:
    - external: traefik.main.kfirs.com.
---
apiVersion: v1
kind: Service
metadata:
  name: greenstar-redis
spec:
  ports:
    - name: client-nontls
      port: 6379
      protocol: TCP
      targetPort: client-nontls
    - name: client-tls
      port: 6380
      protocol: TCP
      targetPort: client-tls
  selector:
    app.kubernetes.io/component: redis
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: greenstar-redis-tls-tcp
spec:
  entryPoints: [redis]
  routes:
    - match: HostSNI(`greenstar-redis.default.kfirs.com`)
      middlewares:
        - name: ip-whitelist
          namespace: traefik
      services:
        - name: greenstar-redis
          port: client-tls
  tls:
    passthrough: true
    secretName: greenstar-redis-kfirs-com-tls
